export const homeData = [
    {
      id: 1,
      name: "Tarzan",
      rating: 4.7,
      time: "1hr : 50mins",
      desc: "Tarzan, having acclimated to life in London, is called back to his former home in the jungle to investigate the activities at a mining encampment.",
      starring: "Alexander Skarsgård, Samuel L. Jackson",
      genres: "Action",
      tags: "Action, Adventures, Fantasy",
      cover: "../images/home1.jpg",
      video: "../video/video1.mp4",
      date: "13-Dec-2005",
    },
    {
      id: 2,
      name: "Jungle Book",
      rating: 4.6,
      time: "1hr : 35mins",
      desc: "After a threat from the tiger Shere Khan forces him to flee the jungle, a man-cub named Mowgli embarks on a journey of self discovery with the help of panther Bagheera and free-spirited bear Baloo. ",
      starring: "Neel Sethi, Bill Murray",
      genres: "Adventures",
      tags: "Adventures, Drama",
      cover: "../images/home2.jpg",
      video: "../video/video2.mp4",
      date: "15-APL-2016",
    },
    {
      id: 3,
      name: "Lion King",
      rating: 4.8,
      time: "1hr : 58mins",
      desc: "After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery. ",
      starring: "Donald Glover, Seth Rogen",
      genres: "Musical Drama",
      tags: "Musical Drama, Adventures",
      cover: "../images/home3.jpg",
      video: "../video/video3.mp4",
      date: "19-JUL-2019",
    },
    {
      id: 4,
      name: "Peter Pan",
      rating: 4.9,
      time: "1hr : 53mins",
      desc: "The Darling family children receive a visit from Peter Pan, who takes them to Never Never Land where an ongoing war with the evil Pirate Captain Hook is taking place.",
      starring: "Jeremy Sumpter, Jason Isaacs",
      genres: "Fantasy",
      tags: "Fantasy, Action",
      cover: "../images/home4.jpg",
      video: "../video/video4.mp4",
      date: "9-DEC-2003",
    },
  ]
  export const upcome = [
    {
      id: 1,
      cover: "../images/upcome/u1.jpg",
      name: "Snow White and the Huntsman",
      time: "2hr : 07mins",
    },
    {
      id: 2,
      cover: "../images/upcome/u2.jpg",
      name: "Enchanted",
      time: "1hr : 47mins",
    },
    {
      id: 3,
      cover: "../images/upcome/u3.jpg",
      name: "Spider-Man",
      time: "2hr : 01mins",
    },
    {
      id: 4,
      cover: "../images/upcome/u4.jpg",
      name: "The Gurdians Of The Galaxy",
      time: "2hr : 01mins",
    },
    {
      id: 5,
      cover: "../images/upcome/u5.jpg",
      name: "Black Panther",
      time: "2hr : 14mins",
    },
  ]
  export const latest = [
    {
      id: 1,
      cover: "../images/upcome/u6.png",
      name: "Hulk",
      time: "2hr : 18mins",
    },
    {
      id: 2,
      cover: "../images/upcome/u7.jpg",
      name: "Caption America",
      time: "2hr : 04mins",
    },
    {
      id: 3,
      cover: "../images/upcome/u1.jpg",
      name: "Snow White and the Huntsman",
      time: "2hr : 07mins",
    },
    {
      id: 4,
      cover: "../images/upcome/u5.jpg",
      name: "Black Panther",
      time: "2hr : 14mins",
    },
    {
      id: 5,
      cover: "../images/upcome/u4.jpg",
      name: "The Gurdians Of The Galaxy",
      time: "2hr : 38mins",
    },
  ]
  
  export const trending = [
    {
      id: 1,
      name: "King Kong",
      rating: 4.7,
      time: "2hr : 35mins",
      desc: "A greedy film producer assembles a team of moviemakers and sets out for the infamous Skull Island, where they find more than just cannibalistic natives.",
      starring: "Naomi Watts, Jack Black",
      genres: "Action",
      tags: "Action, Adventures, Fantasy",
      cover: "../images/img/slide1.png",
      date: "13-Dec-2005",
    },
    {
      id: 2,
      name: "Dinosaur",
      rating: 4.6,
      time: "1hr : 22mins",
      desc: "An orphaned dinosaur raised by lemurs joins an arduous trek to a sanctuary after a meteorite shower destroys his family home. ",
      starring: "Brenda Chapman, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures, Animation, Drama",
      cover: "../images/img/slide2.jpg",
      date: "19-MAY-2000",
    },
    {
      id: 3,
      name: "Aladin",
      rating: 4.8,
      time: "2hr : 08mins",
      desc: "A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true. ",
      starring: "Will Smith, Mena Massoud",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "../images/img/slide3.jpg",
      date: "8-MAY-2019",
    },
  ]
  export const recommended = [
    {
      id: 4,
      cover: "../images/rec/rec1.jpg",
      name: "The Little Mermaid",
      time: "1hr : 23mins",
    },
    {
      id: 5,
      cover: "../images/rec/rec2.jpg",
      name: "Herbie",
      time: "1hr : 41mins",
    },
    {
      id: 1,
      cover: "../images/rec/rec3.jpg",
      name: "Hercules",
      time: "1hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/rec/rec4.jpg",
      name: "Hercules",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/upcome/u3.jpg",
      name: "Spiderman",
      time: "2hr : 01mins",
    },
  ]